package Model;

import java.util.ArrayList;

public class CardNames {
    public static ArrayList<String> skellige = new ArrayList<>();
    public static ArrayList<String> neutral = new ArrayList<>();
    public static ArrayList<String> scoiaTael = new ArrayList<>();
    public static ArrayList<String> nilfgaard = new ArrayList<>();
    public static ArrayList<String> northern = new ArrayList<>();
    public static ArrayList<String> monsters = new ArrayList<>();

    public static void fillArrayLists() {
        skellige.add("Mardroeme");
        skellige.add("Berserker");
        skellige.add("Vidkaarl");
        skellige.add("Svanrige");
        skellige.add("Udalryk");
        skellige.add("DonarAnHindar");
        skellige.add("ClanTordarrochArmorsmith");
        skellige.add("ClanAnCraite");
        skellige.add("MadmanLugos");
        skellige.add("BlueboyLugos");
        skellige.add("Cerys");
        skellige.add("Kambi");
        skellige.add("Hemdall");
        skellige.add("BirnaBran");
        skellige.add("ClanDrummondShieldmaiden");
        skellige.add("ClanDimunPirate");
        skellige.add("ClanBrokvarArcher");
        skellige.add("Ermion");
        skellige.add("Hjalmar");
        skellige.add("YoungBerserker");
        skellige.add("YoungVidkaarl");
        skellige.add("LightLongship");
        skellige.add("WarLongship");
        skellige.add("DraigBon-Dhu");
        skellige.add("Olaf");
        skellige.add("HolgerBlackhand");

        neutral.add("BitingFrost");
        neutral.add("ImpenetrableFog");
        neutral.add("TorrentialRain");
        neutral.add("SkelligeStorm");
        neutral.add("ClearWeather");
        neutral.add("Decoy");
        neutral.add("Commander’shorn");
        neutral.add("Scorch");
        neutral.add("Dandelion");
        neutral.add("EmielRegis");
        neutral.add("ZoltanChivay");
        neutral.add("GaunterO,Dimm");
        neutral.add("GaunterO’DimmDarkness");
        neutral.add("MysteriousElf");
        neutral.add("OlgierdVonEverc");
        neutral.add("TrissMerigold");
        neutral.add("GeraltofRivia");
        neutral.add("Vesemir");
        neutral.add("Villentretenmerth");
        neutral.add("YenneferofVengerberg");
        neutral.add("Cow");
        neutral.add("Chort");

        monsters.add("Draug");
        monsters.add("Leshen");
        monsters.add("Imlerith");
        monsters.add("Toad");
        monsters.add("Kayran");
        monsters.add("ArachasBehemoth");
        monsters.add("CroneWeavess");
        monsters.add("CroneWhispess");
        monsters.add("CroneBrewess");
        monsters.add("EarthElemental");
        monsters.add("FireElemental");
        monsters.add("Fiend");
        monsters.add("Forktail");
        monsters.add("Werewolf");
        monsters.add("PlagueMaiden");
        monsters.add("Griffin");
        monsters.add("Botchling");
        monsters.add("Frightener");
        monsters.add("Botchling");
        monsters.add("GraveHag");
        monsters.add("IceGiant");
        monsters.add("VampireKatakan");
        monsters.add("Arachas");
        monsters.add("VampireBruxa");
        monsters.add("VampireEkimmara");
        monsters.add("VampireFleder");
        monsters.add("VampireGarkain");
        monsters.add("Cockatrice");
        monsters.add("Endrega");
        monsters.add("Wyvern");
        monsters.add("Gargoyle");
        monsters.add("Foglet");
        monsters.add("Harpy");
        monsters.add("CelaenoHarpy");
        monsters.add("Nekker");
        monsters.add("Ghoul");

        nilfgaard.add("ImperaBrigadeGuard");
        nilfgaard.add("StefanSkellen");
        nilfgaard.add("ShilardFitz-Oesterlen");
        nilfgaard.add("YoungEmissary");
        nilfgaard.add("CahirMawrDyffrynAepCeallach");
        nilfgaard.add("VattierDeRideaux");
        nilfgaard.add("Puttkammer");
        nilfgaard.add("AssirevarAnahid");
        nilfgaard.add("FringillaVigo");
        nilfgaard.add("BlackInfantryArcher");
        nilfgaard.add("TiborEggebracht");
        nilfgaard.add("RenualdAepMatsen");
        nilfgaard.add("RottenMangonel");
        nilfgaard.add("HeavyZerrikanianFireScorpion");
        nilfgaard.add("ZerrikanianFireScorpion");
        nilfgaard.add("SiegeEngineer");
        nilfgaard.add("MorvranVoorhis");
        nilfgaard.add("Cynthia");
        nilfgaard.add("Albrich");
        nilfgaard.add("EtolianAuxiliaryArchers");
        nilfgaard.add("MennoCoehoorn");
        nilfgaard.add("LethoofGulet");
        nilfgaard.add("Morteisen");
        nilfgaard.add("Rainfarn");
        nilfgaard.add("NausicaaCavalryRider");
        nilfgaard.add("SiegeTechnician");
        nilfgaard.add("Sweers");
        nilfgaard.add("Vanhemar");
        nilfgaard.add("Vreemde");

        northern.add("Ballista");
        northern.add("Trebuchet");
        northern.add("BlueStripesCommando");
        northern.add("Catapult");
        northern.add("DragonHunter");
        northern.add("DunBannerMedic");
        northern.add("EsteradThyssen");
        northern.add("JohnNatalis");
        northern.add("VernonRoche");
        northern.add("KaedweniSiegeExpert");
        northern.add("PhilippaEilhart");
        northern.add("PoorFuckingInfantry");
        northern.add("PrinceStennis");
        northern.add("RedanianFootSoldier");
        northern.add("SabrinaGlevissing");
        northern.add("SheldonSkaggs");
        northern.add("SiegeTower");
        northern.add("SiegfriedofDenesle");
        northern.add("Ves");
        northern.add("SigismundDijkstra");
        northern.add("SíledeTansarville");
        northern.add("KeiraMetz");
        northern.add("Thaler");
        northern.add("YarpenZirgrin");
        northern.add("Dethmold");

        scoiaTael.add("ElvenSkirmisher");
        scoiaTael.add("Iorveth");
        scoiaTael.add("Seasenthessis");
        scoiaTael.add("Eithne");
        scoiaTael.add("Yaevinn");
        scoiaTael.add("Filavandrel");
        scoiaTael.add("BarclayEls");
        scoiaTael.add("Ciaranaep");
        scoiaTael.add("DennisCranmer");
        scoiaTael.add("DolBlathannaScout");
        scoiaTael.add("DolBlathannaArcher");
        scoiaTael.add("DwarvenSkirmisher");
        scoiaTael.add("HavekarHealer");
        scoiaTael.add("HavekarSmuggler");
        scoiaTael.add("IdaEmeanaep");
        scoiaTael.add("Riordain");
        scoiaTael.add("Toruviel");
        scoiaTael.add("VriheddBrigadeRecruit");
        scoiaTael.add("VriheddBrigadeVeteran");
        scoiaTael.add("Milva");
        scoiaTael.add("Schirru");
        scoiaTael.add("IsengrimFaoiltiarna");
        scoiaTael.add("MahakamanDefender");


    }
}
